services:
  kasa-simple-api:
    image: christracy/kasa-simple-api
    container_name: kasa-simple-api
    environment:
      - TZ=America/Chicago
      - API_KEY=supersecret123
    restart: unless-stopped
    ports:
      - "8000:8000"